[workspace]
channels = ["conda-forge"]
name = "Practical_Metabolic_modelling"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.14.*"
cobra = ">=0.32.1,<0.33"
matplotlib = ">=3.11.1,<4"
numpy = ">=2.5.3,<3"
notebook = ">=7.6.2,<8"

[pypi-dependencies]
steadiercom = ">=0.1.5,<0.2"
